hugoblox:
  schema: "2.0"
  identity:
    name: Jer Steeger
    type: person
    tagline: Philosopher of Physics
    description: Dr. Jer Steeger is a philosopher of physics taking a pluralist approach to issues in quantum foundations and physics education.
    organization: University of Bristol
  theme:
    mode: system
    pack: minimal
    colors:
      primary: "#582f84"
      secondary: "purple"
      neutral: ""
  typography:
    font: sans
    size: md
    pack: academic
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: right
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
